language: node_js
node_js:
  - "0.12"
  - "0.11"
  - "0.10"

before_script:
  - export DISPLAY=:99.0
  - export CHROME_BIN=chromium-browser
  - sh -e /etc/init.d/xvfb start
  - chmod +x ./node_modules/karma/bin/karma
script: phantomjs test/qunit/run-qunit.js "http://localhost:80/test/index.html"
branches:
  only:
    - gh-pages
